### ISSUE TITLE
Outdated installation documentation

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/isopretGO#146]
The documentation in [README.md](https://github.com/TheJacksonLaboratory/isopretGO/blob/master/README.md) is out of date, at least in section “Note to Macintosh users”. On an M2 Macintosh, I could not get the pre-built installation file for Isopret to work, even with Java versions lower or higher than 17.0.2. However, I tried it on an M2, but the README.md refers to M1.

Only after following the link [PACKAGE](https://github.com/TheJacksonLaboratory/isopretGO/blob/master/PACKAGE.md) in the "Note to Linux users" section, I was able to build a `dmg` file for Isopret using the documentation provided there, which I could then install and run. However, the version number in the `dmg` file name is specified incorrectly. I built it using version `1.0.1` but the name was: `isopret-gui-1.0.0.dmg`. By the way, the entire installation procedure also worked with Java `17.0.8`, not just for `17.0.1`.

I did not test installing Isopret on Linux.

This issue is related to Issue #127.

**Comment by pnrobinson** [comment]
I have updated the README.
We will need to test more widely but for now it seems the JAR file is working on Mac (M1/M2) and linux.
