### ISSUE TITLE
Incomplete ReadTheDocs documentation

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/isopretGO#150]
HBA-Deals output files are required as input for the analyses that can be performed with the GUI. The documentation describes the format of HBA-Deals output files and where to find a large collection of such files (https://zenodo.org/record/6483996). However, some other input files are required, which are downloaded from the setup screen. What these files are and where they come from (https://zenodo.org/record/6466530/) is described in a section about the command line interface of the GUI. However, the GUI itself is still undocumented.

It should at least be described which analyzes and screens (Setup, Analysis, DGE, DAS, …) are available and how the various results and representations are to be interpreted. Furthermore, the input parameters for the ontology term enrichment analysis at isoform level (Term for term, Parent-Child union, Bonferroni, Sidak, etc.) should be explained. And finally, the exported files should also be described.

**Comment by pnrobinson** [comment]
We should point here for HBA Deals - https://thejacksonlaboratory.github.io/HBA-DEALS/
We need some material for edgeR though.
