### ISSUE TITLE
Input files provided for IsopretGUI out of date

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/isopretGO#151]
The documentation refers to a Zenodo repository (https://zenodo.org/record/6483996), which provides 100 input files for isopretGUI, which were created using HBA-Deals. These files are out of date. Due to changes in RNA-seq/HBA-Deals pipeline, the numbers of differentially expressed and spliced genes have changed. These files should be updated. Furthermore, the code for the pipeline used should be specified. Beyond HBA-Deals output files, isopretGUI requires additional input files that are provided in a second Zenodo repository (https://zenodo.org/record/6466530). These files should also be checked to make sure they are up to date and updated if necessary.

**Comment by pnrobinson** [comment]
@karleg 
Could we update the zenodo as described above? It would probably make sense to include the 100 input files and also the COVID files if possible.
I think the files in the second repository are still up to date though?

**Comment by karleg** [comment]
I don't have an option to update, either because it's not possible or because the permissions are not set that way.  If it's not possible to update,  I could create another archive?

**Comment by hansenp** [comment]
We do not allow modification (add, remove, modify) of files after it has been published. Instead, you can use our [versioning](https://help.zenodo.org/docs/deposit/manage-versions/) to create a new version of the record.

**Comment by pnrobinson** [comment]
The zenodo has been updated in the manuscript.
