### ISSUE TITLE
Incomplete display of isoform plot

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/isopretGO#152]
In the plot for isoforms of a gene, green and red bars are used to represent fold changes graphically.

For large fold changes, the bar protrudes from the displayed area:

<img width="1266" alt="image" src="https://github.com/TheJacksonLaboratory/isopretGO/assets/10495485/223a6d56-0ddc-4bbd-9aa9-58f23afdb5dd">

The full plot is as follows:

<img width="1250" alt="image" src="https://github.com/TheJacksonLaboratory/isopretGO/assets/10495485/660c3c3c-56b0-402e-b9bd-a703bba08973">

For large negative fold changes, the bar overlaps with elements below it:

<img width="1264" alt="image" src="https://github.com/TheJacksonLaboratory/isopretGO/assets/10495485/42ac6054-1078-412c-b70d-897aeb480453">

**Comment by pnrobinson** [comment]
Good point. It is hard to create a plot like this dynamically that works well with all values - either we have extra white space or things overlap. Maybe it would be better to put the gene expression somewhere else altogether or otherwhise change the layout of the plot? Ideas? I am thinking it might be best to put the gene expression to the right of the transcript bars?

**Comment by pnrobinson** [comment]
PS, make changes together with issue https://github.com/TheJacksonLaboratory/isopretGO/issues/136

**Comment by pnrobinson** [comment]
I have reworked the layout to look like this -- it can always be improved furhter but I think this will help with the issue mentioned above. I am going to work on the other issues today and then would close this unless there are major problems left over!

![Screenshot 2023-12-13 at 10 38 46](https://github.com/TheJacksonLaboratory/isopretGO/assets/4943420/25d91e28-343e-4ca4-9173-7d53f3fdaf38)

**Comment by hansenp** [comment]
Perhaps we could also show the bars for the isoforms horizontally and center them at fold-change 0. But centering might be difficult. One thing that would probably be easy to do would be to omit the gene symbols on the isoforms and just show the isoform IDs.

**Comment by pnrobinson** [comment]
Let's omit the gene symbols for the isoforms -- for the rest, let's leave for now, it is suprisingly difficult to get the spacing to work in general and it is more or less working now!

**Comment by pnrobinson** [comment]
fixed for now
