### ISSUE TITLE
Lexicographical sorting of probabilities (PEPs) on analysis screen

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/isopretGO#154]
On the analysis screen, genes are listed in a table. By clicking on one of the header cells, the table can be sorted by the corresponding column. The "**Fold change**” column will be sorted numerically, which makes sense, but the “**PEP (Expression)**” and “**PEP (Splicing)**” columns will be sorted lexicographically.

<img width="1352" alt="image" src="https://github.com/TheJacksonLaboratory/isopretGO/assets/10495485/080eeec3-5f79-4ab1-8155-78b0501df355">

**Comment by pnrobinson** [comment]
The sorting is numerical. In the picture above, if you click on the triangle next to PEP (Expression), it will change the order of the search and show the best hits on top. I just rechecked that everything is working, but if I am missing something please reopen.
