### ISSUE TITLE
Analysis screen: Permanent coloring of cells when filtering for gene symbol

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/isopretGO#155]
When I filter the table for a gene symbol, some cells in columns “PEP (Expression)” and “PEP (Splicing)” remain colored even though no content is displayed.

<img width="1329" alt="image" src="https://github.com/TheJacksonLaboratory/isopretGO/assets/10495485/11f4ec5c-5c0f-4708-8d4f-88bc840091e1">

**Comment by pnrobinson** [comment]
I have tried this in many different combinations. I can reproduce this error, but it seems to occur in less than 5% of the cases, and it disappears when you erase the gene from the search field. I am guessing this is an issue with the JavaFX implementation and not an error in our code, and there is no obvious way to influence this behavior. Please also try to update your Java installation to 21. I have also updated the versions of the JavaFX, maybe this is also helping.
