### ISSUE TITLE
DGE Screen > GO enrichment: Bar chart compressed due to long GO labels

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/isopretGO#156]
From the DGE screen, a window can be opened in which a bar chart is shown. The bar chart is compressed more or less depending on how long the longest GO label is.

<img width="900" alt="image" src="https://github.com/TheJacksonLaboratory/isopretGO/assets/10495485/7b2b158a-afc5-4afd-a2cb-f1e325975709">

**Comment by pnrobinson** [comment]
The only way to fix this was to limit the maximum length of the GO labels to 40 characters, which looks a lot better. As far as I can see, there is no way to wrap long labels on multiple lines without making our own widget to do so...
But it is better now.
