### ISSUE TITLE
isopretGUI reports slightly different numbers for the same input on different machines

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/isopretGO#159]
We noticed that isopretGUI reports slightly different numbers of differentially expressed genes, differentially spliced genes, etc. for the same input file from HBA-Delas on different machines (table at the top of the analysis screen).

For file `SRP119676_240.txt` from the [Zenodo](https://zenodo.org/record/6483996) repository with MD5 checksum `987bbc84fc2595a137f7eae2ae314013`, the following numbers were reported on a Mac M2:

<img width="1130" alt="image" src="https://github.com/TheJacksonLaboratory/isopretGO/assets/10495485/577559ba-89e3-4abc-800c-7fc63d8a0ded">

And on a Core i7 machine, the following numbers were reported:

<img width="1216" alt="image" src="https://github.com/TheJacksonLaboratory/isopretGO/assets/10495485/2151edf0-9154-4792-9dde-96219aced187">

In both cases the `dmg` file for isopretGUI was created using `bash package.sh`.

To narrow down the error further, it would be good if others could create such screenshots using the same file and post them here.

**Comment by pnrobinson** [comment]
This is worrisome, I will try to track this down.
I am thinking it might be better to try and improve the modularity of the code for better testing.

**Comment by pnrobinson** [comment]
@hansenp  I tested the above examples on my M1 mac. Note sure if this is a mistake but you are showing different genes (CS and UQCRQ on top but GK and FGGY on the bottom). In any case I get the same numbers as shown above.

**Comment by hansenp** [comment]
I tested again with the same file (`SRP119676_240.txt`) on the same computer (M2) as above, but with the latest version of isopretGUI. Here is the resulting table with the summary statistics:

<img width="806" alt="image" src="https://github.com/TheJacksonLaboratory/isopretGO/assets/10495485/00da14ae-da30-494e-a548-fafc7ea5d87e">

Only the values for _Significant DGE GO Terms_ and  _Significant DAS GO Terms_ changed slightly. The remaining values are unchanged.

@pnrobinson Do you get the same results on your computer?

**Comment by pnrobinson** [comment]
I am getting different numbers for the genes (fold changes). Could we do this together to check @hansenp  ?

**Comment by pnrobinson** [comment]
This was a different version,
md5sum SRP119676_240.txt 
da1cf681165cfb4aae2b7a4dedfb3e77  SRP119676_240.txt

**Comment by hansenp** [comment]
I used the jar file from the latest release:

https://github.com/TheJacksonLaboratory/isopretGO/releases/tag/1.3.2

and default parameters.

**Comment by koehlek99** [comment]
I also tested with SRP119676_240.txt using the latest release, it's almost the same as yours @hansenp. One significant DGE GO term is missing 

![image](https://github.com/TheJacksonLaboratory/isopretGO/assets/54836838/c484ba3e-f26d-4355-93af-1ef25550e00d)
